env:
  browser: true
  commonjs: true
  es6: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  {
    comma-dangle: 0,
    implicit-arrow-linebreak: 0,
    function-paren-newline: 0,
    no-await-in-loop: 0,
    no-restricted-syntax: 0,
    no-underscore-dangle: 0,
    prefer-destructuring: 0,
    no-unused-vars: 1,
  }
